name: Invoke Pester Tests

on:
  workflow_call:

jobs:
  test-module:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Pester Module
        shell: pwsh
        run: |
          Set-PSRepository -Name PsGallery -InstallationPolicy Trusted
          if (-not (Get-Module -ListAvailable -Name Pester)) {
            Install-Module -Name Pester -RequiredVersion 5.7.1 -Confirm:$false -Force
          }

      - name: Run Tests
        shell: pwsh
        run: |
          Import-Module -Name Pester -Force
          Invoke-Pester -Path Tests
