name: Invoke Pester Tests

on:
  workflow_call:
    secrets:
      ENV_VARIABLES:
        description: "Serialized environment variables (base64 encoded JSON)"
        required: false

jobs:
  test-module:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Load environment variables
        if: env.ENV_VARIABLES
        run: |
          $json = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:ENV_VARIABLES))
          $obj = ConvertFrom-Json $json
          $obj.PSObject.Properties | % {
          $key = $_.Name
          $value = $_.Value
          Write-Host "Setting environment variable: $Key=********" -ForegroundColor Green
          Set-Item "env:$key" $value
          echo "$key=$value" >> $env:GITHUB_ENV
          }
        shell: pwsh
        env:
          ENV_VARIABLES: ${{ secrets.ENV_VARIABLES }}

      - name: Install Pester Module
        shell: pwsh
        run: |
          Set-PSRepository -Name PsGallery -InstallationPolicy Trusted
          if (-not (Get-Module -ListAvailable -Name Pester)) {
            Install-Module -Name Pester -RequiredVersion 5.7.1 -Confirm:$false -Force
          }

      - name: Run Tests
        shell: pwsh
        run: |
          Import-Module -Name Pester -Force
          Invoke-Pester -Path Tests
